language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.1
- 2.2
- 2.3.0
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-logs.gemspec
- gem install sensu-plugins-logs-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: aXcvXQGeBoeTI5KsjzmF1YjoSD1JkbVi0dQOqHI4FnPZka0WdFwMIsvbVg8bFMQ8A7N/ad/zuyj3wsDD/MAN8DTsPNeS9OYwpEl2ODRuzVUa3gwJfc2GDo1x5QTBCFKHfjyddV8GvOPg1dEKZ2l5HKgNGVsEfVEU3FbBIkEW6c4=
  gem: sensu-plugins-logs
  on:
    tags: true
    all_branches: true
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    repo: sensu-plugins/sensu-plugins-logs
